<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>Easy_Tags</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Zenger.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\ZG_Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Zenger.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\ZG_Logo.png" />
  </ItemGroup>

</Project>
